### ISSUE TITLE
About the images in posts 

### ISSUE THREAD

**Issue by moikonna** [perttuvaarala/CatchMaster#34]
Can We store the whole image to mongodb instead of the planed image link? Mongo should support files up to 16MB and this would improve user experience a lot by removing need for third party image link. Found a post about this topic that gives more insight to saving images to mongo [article](https://www.geeksforgeeks.org/upload-and-retrieve-image-on-mongodb-using-mongoose/). Can @adnanavni please take a look at this and see if our database can handle this?

**Comment by adnanavni** [comment]
we would have to use blob storage and its expensive :D we can maybe try imgur api and post picutres in imgur and use the link, the user would have the opportunity to load images 🔥
