### ISSUE TITLE
Käyttäjänä haluan kirjautua nettisivulle Google tunnuksillani

### ISSUE THREAD

**Issue by adnanavni** [perttuvaarala/CatchMaster#7]
**Hyväksymiskriteerit**
Vain ja ainoastaan Google authorization! ei muuta mahdollisuutta kirjautua

**Valmis kun:**
Ominaisuus on integroitu pääsovellukseen ja on käyttövalmis.

**Comment by moikonna** [comment]
Google authorization now available and working this issue can be closed now.
